### ISSUE TITLE
Trigger the flip event from outside the Div ?

### ISSUE THREAD

**Issue by apatikgg** [nnattawat/flip#107]
I just found out about your flip.js and it might just be what I was trying to achieve on my own.  
Is it possible to trigger the flip event from outside the div ? For instance :  

```
<div id="flip-left">Click me to flip Card to the left</div>
<div id="flip-right">Click me to flip Card to the right</div>
<div id="card"> 
  <div class="front"> 
    Front content
  </div> 
  <div class="back">
    Back content
  </div> 
</div>
```

I didn't see this functionnality mentionned so I thought I would ask here. Thank you !

**Comment by JemarJones** [comment]
Yea, just use the manual flip. You can see similar stuff on the project page http://nnattawat.github.io/flip/
