### ISSUE TITLE
Flipping Tables

### ISSUE THREAD

**Issue by alex-martin-xactium** [nnattawat/flip#11]
So i have a set of tables, divs and various other html components on a single white background div. This is the front. The back, has the same contents, just different data on the same coloured white background.

When flipping, as it get towards the middle, the background table starts to flicker through in a strange effect, as though the browser is trying to adjust for the changing components. Any idea on how to fix this? 

If this doesn't make any sense, i'll make a quick video. 

Also, after slowing the animation right down (11,700), I notice that the flickering only happens on the rear tile. It's the contents of the front tile flickering through. 

A possible solution would be to some how detect that the flip is 50% through, and set the background tile to display:none

**Comment by nnattawat** [comment]
Is your example accessible online somewhere?

**Comment by alex-martin-xactium** [comment]
Unfortunately not, it's being used in a closed system. 

I think it's an issue with Chrome/Firefox. Trying it on IE just flips it in a strange direction, but it looks pretty nice.

**Comment by Download** [comment]
I have seen similar issues in the past and (I think) fixed it. I did not use the suggested `display:none`, but something similar: I set `z-index:0` for the face which is currently not showing and `z-index:1` for the face which is showing. This resolved it for me.

Closing this issue. Please test with v1.0.12 or later and re-open if you still have issues.
