### ISSUE TITLE
Force Flip to Front

### ISSUE THREAD

**Issue by sanjshah** [nnattawat/flip#110]
Hi,

I have ani issue when I view my pae on an iPad, my question is whether I can force the view (flip) to fron or back via javascript.

Any help is appreciated.

**Comment by nnattawat** [comment]
Yep
```
// flip to the front
$("#your_dom").flip(true);

// flip to the back
$("#your_dom").flip(false);
```

**Comment by sanjshah** [comment]
Thanks!
