### ISSUE TITLE
How to reinitiate flip?

### ISSUE THREAD

**Issue by matejmosko** [nnattawat/flip#111]
Hello,
I need to know if it is possible to reinitiate .flip namespace on a selector after I have turned it off with

`$(this).off(".flip");`

I have already tried

```
$( this ).flip({
          trigger: 'hover'
        });
```

but with no success.

**Comment by wzzwwbx** [comment]
Same question here.

**Comment by lmdunklee29** [comment]
Same question here

**Comment by lmdunklee29** [comment]
http://stackoverflow.com/questions/43595432/reinitiate-flip-js/43598450#43598450

See this thread - the answer worked for my issue.
