### ISSUE TITLE
Very funny problem

### ISSUE THREAD

**Issue by homawog** [nnattawat/flip#142]
Hello all,

I have a recent problem with one of my web applications where I use the plugin jQuery Flip.
It used to work flawlessly, and since I don't use the web application that often anymore, I found out relatively late that a very strange phenomenon is occurring.
It is very difficult to describe, in principle the flip works, but the animation goes over the whole window and is therefore very unsightly.
Since I do not know exactly since when the problem occurred, I have now used some older versions of jQuery Flip to check whether I can clean up the problem, but unfortunately had no success.
I attached a short video where you can see the problem and have the link to my application here (http://homawog.bplaced.net/ChordInversions/ChordInversions.php).
Maybe anyone has had a similar problem and may have a solution, I'm a bit at a loss.

Many thanks and kind regards
Martin

https://user-images.githubusercontent.com/96771161/147790329-57b60faf-92da-4197-a107-940c4421de21.mp4

**Comment by nemeros111** [comment]
You can fix it by adding this css:

#card{ 
perspective: 100px !important;
}

**Comment by homawog** [comment]
Hello nemeros111, you are my hero. I read up on what this attribute means, which I didn't know and didn't use before, and then experimented a bit with it and found the ideal value for my page with the value 400px.
Thank you very much and stay healthy
Martin

**Comment by ChrisMiami** [comment]
I'm so glad I looked for existing issues before filing on this same behavior.

https://github.com/nnattawat/flip/assets/4670942/d6aff8f4-467d-4baf-83da-c9e6cd43c963

**Comment by ChrisMiami** [comment]
I'm so glad I checked here before filing a new bug on this same behavior.  It was so disappointing to see it happening but I'm equally relieved there's a simple fix.

https://github.com/nnattawat/flip/assets/4670942/b2e665ee-76eb-4bb3-a90a-56bc990be862
