### ISSUE TITLE
Add support for flippable content with dynamic height/width

### ISSUE THREAD

**Issue by Download** [nnattawat/flip#17]
Currently, Flip fixes the width and height of the content by adding width and height styles forcing dimensions in pixels. In my fork I prepared a version of Flip that does not do this, allowing the width and height to be controlled from the stylesheet and be percentages so it shrinks/expands with the container it's in.

**Comment by timsamuelsson** [comment]
+1

**Comment by softdays** [comment]
+1 (I have to use Download's fork to flip content with dynamic height)

**Comment by JemarJones** [comment]
+1 This should definitely be merged, it just makes sense.
