### ISSUE TITLE
flip state

### ISSUE THREAD

**Issue by halmsx** [nnattawat/flip#18]
hi

how do i read the current state of the flip? i want to know which div is currently true and which is currently false. 

thanks in advance.

**Comment by nnattawat** [comment]
For now you can do `$dom.data('fliped');` I will consider to add a method to get the state later.

**Comment by halmsx** [comment]
hi

im getting true from the following.

console.log($("#contact-diamond-card").data('fliped'));

thats sufficient enough i think. thanks!

**Comment by halmsx** [comment]
ok. i see the problem. anyway, the code below works. thanks!

**Comment by nnattawat** [comment]
No problems!
