### ISSUE TITLE
The flip content show in chrome, works in safari

### ISSUE THREAD

**Issue by shakahub** [nnattawat/flip#19]
The content in "back" is dynamically generated by ajax call. When it flips, it shows up in the "front" with reverse order, supposed to be hidden. This does not work only for chrome. Safari works fine. Any ideas?

![screen shot 2015-05-25 at 11 14 47 am](https://cloud.githubusercontent.com/assets/11306816/7800761/5b137694-02cf-11e5-8a42-61e6bb8b2358.png)

**Comment by Download** [comment]
@shakahub 
Can you please test with v1.0.12? 
Some issues have been fixed that resemble your problem.

I am closing this, but if you still have issues feel free to re-open.
