### ISSUE TITLE
backface-visibility, Chrome compatibility.

### ISSUE THREAD

**Issue by devinclava** [nnattawat/flip#38]
Please, add **-webkit-backface-visibility: hidden;** to support outbounding content in Chrome, Safari and Opera.

**Comment by JemarJones** [comment]
I believe that jQuery is supposed to take care of this since v1.8.0 (of jQuery), what version are you using? I'm not actually really aware what version most people are using so I'm not saying no.

**Comment by Download** [comment]
I'm using Flip in a mobile application and Android's default browser only supports the prefixed versions of the rules. Flip is working there as it should so I think Jemar is right and jQuery handles it.

@devinclava Can you let us know where you are having issues with this? A test case maybe?

**Comment by Download** [comment]
Closing, because of lack of response, and both Jemar and myself believe there is not actually an issue here.

**Comment by m-phil** [comment]
OK, there is a current problem with Chrome after updating from version 74.0 to 75.0 when having an element and its child tags (i.e. p, img etc) with

`backface-visibility: hidden;`

Chrome displays the content of the children from the hidden side. 
I fixed it by adding

`faces.css(faceElementCss).find('*').not('p, strong, b, br, img').css({
                "backface-visibility": "hidden"
            });`
in line 202 to avoid to add the backface-visibility on childs.

Maybe it's like double hidden means show?! like in math - and - is + :-)
