### ISSUE TITLE
IE9 support

### ISSUE THREAD

**Issue by BC17** [nnattawat/flip#42]
Any chance to get this awesome plugin work on IE9?

Thanks...

**Comment by Download** [comment]
Please have a look at the [Can I Use support tables for 3D transforms](http://caniuse.com/#feat=transforms3d). IE9 does not support 3D transforms.

If anyone has some smart trick to make it working, we are always open for suggestions of course.

**Comment by Download** [comment]
Also see https://github.com/nnattawat/flip/issues/7

**Comment by BC17** [comment]
what about using GSAP as a fallback?
https://greensock.com/docs/#/HTML5/GSAP/Plugins/CSSPlugin/

**Comment by Download** [comment]
Now, don't get me wrong. I do think it's possible to *simulate* a sorta-3D flip animation on IE9 (maybe even below)... Look at this for example: http://jsfiddle.net/Durdona/qrrvozkb/

The questions are more: Is it worth it? and Who will build it?

Personally i've dropped IE9 support for my current project and it feels *very* liberating. I just write `document.addEventListener('DOMContentReady', ...)` now... without feeling guilty.. :) 
There are now 3 newer versions of Internet Explorer / Edge, all of which are supported. Within a few months there will probably be four and it could start going really fast very soon with MS' new upgrade policies. So I am not interested in pulling the weight for this.

However, that said, if you would like to try and cook something up I (and Jemar also probably) are willing to help you out where needed. If you come up with something that looks good I'd be happy to merge it in.

I'll reopen this for the moment, but I won't be taking the lead in implementing this.

**Comment by JemarJones** [comment]
My views are essentially the same. I don't think it's worth the effort it would take and the bloat it would add to flip.

**Comment by Download** [comment]
The bloat could be dealt with by introducing a 'backward compatibility' version of Flip that contains the extra code... like jQuery does with their v1 vs v2 lines. But it all requires work and for me it's not worth the effort.

**Comment by JemarJones** [comment]
It might be interesting to develop those two versions internally and then load the appropriate one as with http://modernizr.com/docs/#load, I think we would only load the needed one so performance would be okay, and no one else would need to worry about which version they use? But either way this would require writing twice the code every time something is added. So unless someone is willing to step up and take on that extra work I don't see this happening.

**Comment by Download** [comment]
Agreed
