### ISSUE TITLE
flip:done not triggering also backface still showing

### ISSUE THREAD

**Issue by nonaxanon** [nnattawat/flip#47]
maybe its just me, but im using your latest version on latest chrome, and the flip:done seems to not trigger and the backface of the card is always shown, like in https://jsfiddle.net/ycLb142q/  just wanted to see if there was something weird on my side or is this error reproduced by someone else too

**Comment by nonaxanon** [comment]
figured for my set up, i needed to have a div out side the div class"front" or "back" with at least 1 pixel in white, for the backface to be hidden, otherwise it would always show , as on the latter issues here

**Comment by Download** [comment]
Looking at your original Fiddle it was using v1.0.15 of Flip. I changed it to v.1.0.16 and that seemed to resolve the issue:  https://jsfiddle.net/ycLb142q/24/
