### ISSUE TITLE
Option to unregister flip

### ISSUE THREAD

**Issue by c-a-m** [nnattawat/flip#49]
I've been having fun with flip.  Thanks!  

I've built a simple memory game with flip.  Each tile is registered to flip on a click or tap.  But once a match is found, I'd like to turn off flip.  I attempted to call $('#tileId').flip( { trigger: 'manual' } )  but that is my best guess as to how to do it.  Any suggestions?

**Comment by JemarJones** [comment]
In the future flip will work the way you've just described. A little busy lately but I will get around to it soon hopefully.

**Comment by nnattawat** [comment]
As @JemarJones, we can add unbind feature in the next release. For now, you need to `{ trigger: manual }` and control the interaction yourself or you can try unbind the event that you use in the trigger from your DOM, for example, if you use `click` you can do `$('#tileld').unbind('click');`. However, this is a bit tricky as it will unbind all click events from your DOM (not just the flip one). We will add the event namespace in future.

**Comment by c-a-m** [comment]
Thanks for the tip.  I'll do as suggested until some future release.   Thanks again for the fun plugin!

**Comment by nnattawat** [comment]
Flip can be easily unbind from version `v1.0.19` once  #68 is merged
