### ISSUE TITLE
Missing "main" and "ignore" entry in bower.json

### ISSUE THREAD

**Issue by VholtWCP** [nnattawat/flip#50]
When trying to install flip using bower, we get the following error because the "main" and "ignore" entries are missing from bower.json:

bower flip#~1.0.x                              invalid-meta flip is missing "main" entry in bower.json                                                                                                                               
bower flip#~1.0.x                              invalid-meta flip is missing "ignore" entry in bower.json

**Comment by Download** [comment]
Good catch
