### ISSUE TITLE
Same behaviour without back face, only front

### ISSUE THREAD

**Issue by ebaynaud** [nnattawat/flip#57]
I wish flip to work without the back face so only with a front face. Linked to my other enhancement request (360deg instead of 180deg), that would replace totally other libraries I use like rotate3di or jquery transit to get this done.

**Comment by Download** [comment]
Is there a reason not to just have an empty back face?

https://github.com/nnattawat/flip/issues/56

**Comment by ebaynaud** [comment]
If https://github.com/nnattawat/flip/issues/56 is done, that could be sufficient to suite my needs. Let me try tonight and close this one if ok.

**Comment by Download** [comment]
#56 is not done afaik

**Comment by ebaynaud** [comment]
I mean, when it will be done. But I can test it even if it's not there yet and maybe this request has no sense because using an empty element is ok. That is what I want to test.

**Comment by Download** [comment]
> I mean, when it will be done.

Does this mean you are working on a PR?

**Comment by ebaynaud** [comment]
Actually the workaround to repeat the front element as a back element after is totally ok for the moment.

**Comment by Download** [comment]
:+1:
