### ISSUE TITLE
Trigger manual with different speed

### ISSUE THREAD

**Issue by ebaynaud** [nnattawat/flip#58]
Any reason why speed is not taken into account?

```javascript
$(window).load(function () {
    $('.flip-container').flip({trigger: 'manual', speed: 3000});
    $('.flip-container').flip('toggle');
});
```

**Comment by Download** [comment]
Speed is actually the transition time (in ms) so you would expect an inverse effect: higher 'speed' means a slower flip. Are you not seeing this? If so can you make a JSFiddle and we will look at it.

**Comment by Download** [comment]
Closing as dup of https://github.com/nnattawat/flip/issues/59
