### ISSUE TITLE
Change the speed after event

### ISSUE THREAD

**Issue by ebaynaud** [nnattawat/flip#59]
It doesn't seem to be possible but I would like to perform something like that to change speed after first flip:
```javascript
$('.flip-container').flip({trigger: 'manual', speed: 250});
$('.flip-container').flip('toggle');
$('.flip-container').flip({trigger: 'manual', speed: 3000});
```
Any workaround?

**Comment by Download** [comment]
I was under the impression that this should actually work.
Can you prepare a JSFiddle demonstrating it?

**Comment by Download** [comment]
@JemarJones Do you still want to look at this or shall we close it?

**Comment by Download** [comment]
https://github.com/nnattawat/flip/issues/58

**Comment by Download** [comment]
@ebaynaud Do you want to keep this open? If so I suggest you prepare a JSFiddle.

**Comment by ebaynaud** [comment]
Can be closed as I'm not working anymore on that project for the moment


-- 
Erwan

**Comment by Download** [comment]
Ok, thanks for the heads-up.
