### ISSUE TITLE
Still showing checkboxes on flip

### ISSUE THREAD

**Issue by stibay** [nnattawat/flip#61]
I have a table with lots of elements on the front panel and its hiding everything when I flip it except all the checkboxes? Is this a known issue?

**Comment by Download** [comment]
No, not known to us. Can you make a [JSFiddle](https://jsfiddle.net) demonstrating your issue?

**Comment by Download** [comment]
@stibay Are you still having this issue? Did you find a solution/workaround?

**Comment by stibay** [comment]
Ended up going for a different approach.

**Comment by Download** [comment]
:+1:  Ok, thanks for the feedback

**Comment by jarzebowsky** [comment]
https://jsfiddle.net/L6knkw1q/ - same issue with progress bar and <p> markups

It happends on Chrome, Firefox is okey.
