### ISSUE TITLE
Not working with twitter bootstrap 3.3.6

### ISSUE THREAD

**Issue by rasmuschristensen** [nnattawat/flip#69]
When used together with twitter bootstrap, the elements is not hidden when flipped, just reversed.

**Comment by rasmuschristensen** [comment]
Can be tested with this setup

<div id="cardtest">
    <div class="front">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">test</div>
                </div>
            </div>
        </div>
    </div>
    <div class="back"><div class="row">lorem flipsum</div></div>
</div>

**Comment by nnattawat** [comment]
The [demo page](nnattawat.github.io/flip/) use bootstrap `3.3.5` with no problem. Can you try with `3.3.5` just to make sure that it's the version problem?

**Comment by rasmuschristensen** [comment]
Ok I'm running 3.3.6 so version seem not to be the issue. But I managed to find the issue. The issue was I had a div with class row nested inside of front and back. If I put row on the div that's also the front or back, then it wors. Btw. I can see my "try to paste" code above failed a bit :).

**Comment by rasmuschristensen** [comment]
There might also be an issue with nested col divs. But it's only an issue in chrome. I'm on version  47.0.2526.106. IE seems to be ok version 11.0.9600....
