### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by tohood87** [nnattawat/flip#7]
Hi There, 

Was wondering if there was a solution for having this work in Internet Explorer?

**Comment by mapplega** [comment]
I'd like this solution as well, if anyone can get it figured out.

**Comment by jasonspiller** [comment]
This is absolutely beautiful and I have compared a lot of these. Can't wait to see when this bug can be fixed. Thanks for all the hard work.

**Comment by nnattawat** [comment]
Fix with v1.0.1

**Comment by jonathanGB** [comment]
Could it be possible to make it work on IE9 also?
Great plugin by the way!

**Comment by BC17** [comment]
+1 for IE9

**Comment by Download** [comment]
Guys, please have a look at the [Can I Use support tables for 3D transforms](http://caniuse.com/#feat=transforms3d). IE9 does not support 3D transforms.

If anyone has some smart trick to make it working, we are always open for suggestions of course.
