### ISSUE TITLE
Card Stretching on First Load

### ISSUE THREAD

**Issue by richardegil** [nnattawat/flip#71]
When the pages loads for the first time the card flipping elements stretch out. When I refresh the page it works perfectly. Gif below for reference. The second flip is performed after refreshing the page.

Any ideas what could cause this?

http://d.pr/i/18zmB

**Comment by nnattawat** [comment]
Is the width of your element somehow set after calling `.flip()`? Some things seem to be wrong while setting `perspective` which using `outerWidth * 2`
