### ISSUE TITLE
How can this action played auto?

### ISSUE THREAD

**Issue by MrKou47** [nnattawat/flip#77]
i want the box slip itself autoinstands of `onclick` or `hover`,just auto like setInterval.
what trigger should i set ?

**Comment by JemarJones** [comment]
I'm not quite clear on what this issue is about. Can you clarify/provide details?

**Comment by ahgan84** [comment]
I think the user is trying to ask whether we can `setInterval` for it to flip by itself instead of using `onclick` and `hover`. Is there a way?

**Comment by nnattawat** [comment]
In that case you will need to set `trigger: manual` then use JS to flip it manually
```
