### ISSUE TITLE
How do you query the current face?

### ISSUE THREAD

**Issue by nishantpant** [nnattawat/flip#82]
I would like to find out which face is currently being shown? Is there a way to achieve this?

**Comment by JemarJones** [comment]
There isn't currently an official way to do this.

However, the way flip is currently implemented, each card has a data attribute such that the following works:

```javascript
//When the card hasn't been flipped (ie the front face is being shown)
$('#card').data("flipped") == false

//When the card has been flipped (ie the back face is being shown)
$('#card').data("flipped") == false
```

This however is **not** officially part of our API, so i cannot guarantee that this is how it will always work in the future.

I also suspect this could be figured out with a bit of jQuery.
