### ISSUE TITLE
disable plugin on width smaller than ... (minWidth func needed)

### ISSUE THREAD

**Issue by pgarnek** [nnattawat/flip#83]
Hello,
im wondering how simply made functionality, to preserve animation only for certain width (something like minWidth property). I'm not so good in JS yet, maybe there is a simple solution?

Width should be checked on every window resize, to fully work witn responsive and rotating-abled screens (like tablets).

Any sugestions?

**Comment by JemarJones** [comment]
Please give a more exact description of what exactly you are asking for here. It is not clear to me what you are asking from what you've written here.

**Comment by nnattawat** [comment]
You need to manually unregister flip in `$(window).resize()` event. To unregister flip, do  $('element').off('flip');
