### ISSUE TITLE
Card does not perform reverse action with hover trigger and customized speed

### ISSUE THREAD

**Issue by darkicex3** [nnattawat/flip#89]
Hi, 

This code below works perfectly until I add the speed parameter. In this case the card flip on hover event without comeback to his initial position when the mouse exit the card.

Working -> `$(".bigup-button-card").flip({trigger: 'hover'});`
Not Working -> `$(".bigup-button-card").flip({trigger: 'hover', speed: '250'});`

Thanks

**Comment by nnattawat** [comment]
You can use Integer for now as `$(".bigup-button-card").flip({trigger: 'hover', speed: 250});`. I will make it work with string in the next version.

**Comment by darkicex3** [comment]
Ok. Thanks for your answer, it works.

**Comment by nnattawat** [comment]
Fixed on `v1.1.1`.
