### ISSUE TITLE
Trigger flip automatically after being on the page for certain time

### ISSUE THREAD

**Issue by sajpasa** [nnattawat/flip#90]
Hi, is it possible to trigger click automatically after being in the page for 30 seconds or so. I tried using following code but no luck so far
`$(document).ready(function() {
        setTimeout(function() {
          $(".flipImage").flip({
             trigger: 'manual',
             speed: 800
          });
        }, 6000);
    });`

Thanks

**Comment by JemarJones** [comment]
There's no built in functionality for this. You'll need to detect when 30 seconds have passed and then just manually trigger.

**Comment by sajpasa** [comment]
Ok, but I cant seem to get the manual trigger to work. The code above for manual trigger is correct, right?

**Comment by JemarJones** [comment]
In the code you have you have setup a flip object which can be triggered manually, but you haven't actually triggered a flip. To trigger a flip you would execute `$(".flipImage").flip(true);` Please [see the documentation](http://nnattawat.github.io/flip/) in the future.

**Comment by sajpasa** [comment]
My bad, thanks for the help!
