### ISSUE TITLE
Permanent flip, how to unset .flip()

### ISSUE THREAD

**Issue by marijnhurkens** [nnattawat/flip#93]
I am trying to create a situation where a div flips on hover and stays flipped after that. I am trying to achieve this because I have a video playing on the backside and I still want to use _hover_ as the trigger.

I tried the following:

```
$('.showcase').flip({
    axis: 'x',
    trigger: 'hover'
 }).on('flip:done', function() {
    console.log('flipped');
    $(this).off('.flip');
});
```

While the console shows _flipped_ on the flip finish after hovering it still flips back to it's original state and only then destroys the .flip() object.

How do I achieve the correct result?

**Comment by nnattawat** [comment]
I think the easiest is to use trigger: 'manual' and you will just flip it once

**Comment by marijnhurkens** [comment]
Well, off course.. Should have thought about that, solved :)

```
$('.showcase').flip({
    axis: 'x',
    trigger: 'manual'
});
$('.showcase .front').mouseover( function() {
    $(this).closest('.showcase').flip(true);
});
```

**Comment by jarodium** [comment]
A destroy method would be useful if we wanted to replace html contents via ajax and then flip them again.
