### ISSUE TITLE
Item on flip back showing on flip front

### ISSUE THREAD

**Issue by samc36** [nnattawat/flip#94]
I have a card, with an absolutely positioned semi-circle, with a span icon with a negative margin-top above this semi-circle.

This is on both sides of the card, but with a different coloured semi-circle, and a different icon. 

For some reason the icon on the back of the card, is showing on the front until I begin flipping. I've half solved it by using z-index: -1 !important; and then aligning the icons so it's not noticable.

**Comment by nnattawat** [comment]
Try https://github.com/nnattawat/flip/releases/tag/v1.1.2
